### ISSUE TITLE
Typo in `DataCardsExtendedTemplate.md`

### ISSUE THREAD

**Issue by NoB0** [PAIR-code/datacardsplaybook#15]
There is a typo in the section `Access Type` in `DataCardsExtendedTemplate.md`: `External - Open Acess` -> `External - Open Access`.

**Comment by alifiya13** [comment]
Assign me this issue, I'll correct the typo.

**Comment by andrewzaldivar** [comment]
Nice catch! Thank you for calling that out. I've corrected the typo.
