### ISSUE TITLE
[GSOC]: Create a Data Card Using New Template

### ISSUE THREAD

**Issue by andrewzaldivar** [PAIR-code/datacardsplaybook#2]
Several of you have expressed interest in creating your own Data Card. To that end, one of our starter tasks involves using [our new template](https://github.com/PAIR-code/datacardsplaybook/tree/main/templates). 

This template, which you can find [inside the template directory](https://github.com/PAIR-code/datacardsplaybook/tree/main/templates), was created to help onboard developers in creating transparent dataset documentation—while at the same time providing pedagogical practices around transparency. 

Contributions to this starter task will help us explore how this template could scale and adapt across domains. In turn, this starter task provides a general overview of our transparency documentation efforts, and sets expectations for the Benchmark Detectives project.

**This starter task is open for multiple submissions by multiple participants.**

To prepare:
- Choose any dataset out there that does not already have a corresponding Data Card. You may even use datasets that you are currently working on as long as your Data Card will be published with open-access. 
- Gather any existing documentation associated with your selected dataset. If it’s an academic dataset, for example, then this could include its original publication. 
- Explore the [Data Cards Playbook](https://pair-code.github.io/datacardsplaybook/).
- Read [our short paper](https://datacentricai.org/neurips21/papers/112_CameraReady_Data_Cards.pdf) that was recently featured at [NeurIPS 2021 Data-Centric AI Workshop](https://datacentricai.org/neurips21/) to develop a conceptual understanding of Data Cards.

Timeline and submission logistics:
- While filling out a Data Card template can take up to a few hours, keep in mind that needing to conduct additional analysis or investigations could substantially increase the time taken to complete a template.
- If you are using Colab to probe the dataset, train the model, or perform analysis, please include them in your submission.
- When you are done, please commit your completed template to the [Benchmark Detectives directory](https://github.com/PAIR-code/datacardsplaybook/tree/main/benchmarkdetectives) as a Markdown or PDF file. 
- Include a short note on your experience in your proposal for Benchmark Detectives.

**Comment by bhaktipriya** [comment]
GSOC proposals deadline is soon approaching. I highly recommend working on the starter tasks and adding them to your application. This will help set your application apart. Please let us know if you need any help. :) Good luck!

**Comment by aryan1107** [comment]
@bhaktipriya I have also included my starter project for this task here is the PR https://github.com/PAIR-code/datacardsplaybook/pull/10
